
DBDriver pgsql
DBDParams "host=@POSTGRESQLHOSTNAME@ port=@POSTGRESQL_PORT@ dbname=@POSTGRESQL_DATABASE_DATAFARIWEBAPP@ user=@POSTGRESQL_USERNAME@ password=@POSTGRESQL_PASSWORD@ connect_timeout=3"
DBDMin 1
DBDKeep 2
DBDMax 10
DBDExptime 300

# --- Alias AuthN (bcrypt) ---
<AuthnProviderAlias dbd pgsql-users>
  AuthDBDUserPWQuery "SELECT password_bcrypt FROM users WHERE username = %s"
</AuthnProviderAlias>