version: "3"

services:
  cassandra:
    image: 'cassandra:4.0-beta1'
    hostname: 'cassandra'
    ports:
      - '9042:9042'
    environment:
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=128M
    restart: always
    networks:
      - global
  cassandra-load-keyspace:
    build:
      context: .
      dockerfile: DockerfileCassandra
    container_name: cassandra-load-keyspace
    depends_on:
      - cassandra
    networks:
      - global
  postgresql:
    image: 'postgres:12.4'
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - global
  zoo1:
    image: 'zookeeper:3.5.5'
    restart: always
    hostname: zoo1
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
    networks:
      - global
  datafaribuild:
    build:
      context: .
      dockerfile: DockerfileDatafariCompose
    volumes:
      - datafarivolume:/tmp/datafari-webapp/target
      - tikavolume:/tmp/datafari-tika/target
      - solrvolume:/tmp/linux/installer/build/datafari/opt/datafari/solr/solr_home
      - tomcatwarvolume:/tmp/linux/installer/build/datafari/opt/datafari/tomcat/webapps
      - tomcatlibvolume:/tmp/linux/installer/build/datafari/opt/datafari/tomcat/lib
      - tomcatconfvolume:/tmp/linux/installer/build/datafari/opt/datafari/tomcat/conf
    networks:
      - global
  debian:
    image: debian:10
    volumes:
      - datafarivolume:/var/kikoo
    depends_on:
      - datafaribuild
    command: bash -c " cp /var/kikoo/Datafari.war /var/kikoo/super.war && sleep 100000"
  debiantika:
    image: debian:10
    volumes:
      - tikavolume:/var/kikoo
    depends_on:
      - datafaribuild
    command: bash -c " ls && sleep 100000"
  zoomcf1:
    image: 'zookeeper:3.5.5'
    restart: always
    hostname: zoomcf1
    ports:
      - '2184:2181'
    environment:
      ZOO_MAX_CLIENT_CNXNS: 1000
    networks:
      - global
  solr1:
    image: 'solr:8.5'
    ports:
      - '8983:8983'
    environment:
      SOLR_JAVA_MEM: '-Xms1024m -Xmx1024m'
      ZK_HOST: 'zoo1:2181'
      mcf.ip: 'http://datafari:9080/datafari-mcf-authority-service'
    volumes:
      - solrvolume:/var/solr/solrcloud
    networks:
      - global
    depends_on:
      - datafaribuild
  create-collection:
    build:
      context: .
      dockerfile: DockerfileSolr
    container_name: create-collection
    environment:
      SOLR: solr1
      ZK: zoo1
    volumes:
      - solrvolume:/var/solr/solrcloud
    command:
      - bash
      - "-c"
      - "sleep 5; wait-for-solr.sh --max-attempts 10 --wait-seconds 5 --solr-url http://solr1:8983/; /opt/docker-solr/scripts/init-zk.sh"
    depends_on:
      - solr1
    networks:
      - global
  apache:
    build:
      context: .
      dockerfile: DockerfileApache
    restart: always
    hostname: apache
    ports:
      - 80:80
    command: /bin/bash -c 'a2enmod proxy proxy_ajp proxy_http ssl proxy_http auth_digest rewrite headers; a2dissite 000-default ;a2dissite default-ssl ; a2ensite tomcat ; apache2-foreground'
    networks:
      - global
  datafari:
    image: tomcat:9.0.41-jdk11-openjdk-buster
    restart: always
    hostname: datafari
    ports:
      - 8080:8080
    environment:
      - MAIN_DATAFARI_CONFIG_HOME=/opt/datafari/tomcat/conf
      - DATAFARI_SOLR_PROPERTIES_HOME=/opt/datafari/tomcat/conf
      - SOLR_INSTALL_DIR=/opt/datafari/solr
      - CASSANDRA_KEYSPACE=datafari
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    volumes:
      - 'tomcatwarvolume:/usr/local/tomcat/webapps/'
      - 'tomcatlibvolume:/usr/local/tomcat/lib/'
      - 'tomcatconfvolume:/usr/local/tomcat/conf/'
      - 'tomcatconfvolume:/opt/datafari/tomcat/conf/'
    depends_on:
      - datafaribuild
    networks:
      - global
volumes:
  datafarivolume:
  tikavolume:
  solrvolume:
  tomcatwarvolume:
  tomcatlibvolume:
  tomcatconfvolume:

networks:
  global: