/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2015-05-20 14:57:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ajax;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class solr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--Start Breadcrumb-->\n");
      out.write("<div class=\"row\">\n");
      out.write("\t<div id=\"breadcrumb\" class=\"col-xs-12\">\n");
      out.write("\t\t<a href=\"#\" class=\"show-sidebar\"> <i class=\"fa fa-bars\"></i>\n");
      out.write("\t\t</a>\n");
      out.write("\t\t<ol class=\"breadcrumb pull-left\">\n");
      out.write("\t\t\t<li><a href=\"index.html\">Home</a></li>\n");
      out.write("\t\t\t<li><a href=\"#\">Connectors</a></li>\n");
      out.write("\t\t</ol>\n");
      out.write("\t\t<div id=\"social\" class=\"pull-right\">\n");
      out.write("\t\t\t<a href=\"#\"><i class=\"fa fa-google-plus\"></i></a> <a href=\"#\"><i\n");
      out.write("\t\t\t\tclass=\"fa fa-facebook\"></i></a> <a href=\"#\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("\t\t\t<a href=\"#\"><i class=\"fa fa-linkedin\"></i></a> <a href=\"#\"><i\n");
      out.write("\t\t\t\tclass=\"fa fa-youtube\"></i></a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<!--End Breadcrumb-->\n");
      out.write("<div class=\"row-fluid\" style=\"height: 840px;\"> <!-- QUICK AND DIRTY, must be another way using configuration of bootstrap mixins-->\n");
      out.write("    <iframe src=\"proxy/solr/\" width=\"100%\" height=\"100%\" frameborder=\"0\" scrolling=\"yes\"></iframe>\n");
      out.write(" </div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
