//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.24 at 03:27:29 PM CET
//

package com.francelabs.datafari.jaxb;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="query" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="doc" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;simpleContent&gt;
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="exclude" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/simpleContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "query" })
@XmlRootElement(name = "elevate")
public class Elevate {

  protected List<Elevate.Query> query;

  /**
   * Gets the value of the query property.
   *
   * <p>
   * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will
   * be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the query property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   *
   * <pre>
   * getQuery().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list {@link Elevate.Query }
   *
   *
   */
  public List<Elevate.Query> getQuery() {
    if (query == null) {
      query = new ArrayList<Elevate.Query>();
    }
    return this.query;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   *
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="doc" maxOccurs="unbounded" minOccurs="0"&gt;
   *           &lt;complexType&gt;
   *             &lt;simpleContent&gt;
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
   *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
   *                 &lt;attribute name="exclude" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
   *               &lt;/extension&gt;
   *             &lt;/simpleContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *       &lt;/sequence&gt;
   *       &lt;attribute name="text" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   *
   *
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "doc" })
  public static class Query {

    protected List<Elevate.Query.Doc> doc;
    @XmlAttribute(name = "text")
    protected String text;

    /**
     * Gets the value of the doc property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for the doc property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getDoc().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Elevate.Query.Doc }
     *
     *
     */
    public List<Elevate.Query.Doc> getDoc() {
      if (doc == null) {
        doc = new ArrayList<Elevate.Query.Doc>();
      }
      return this.doc;
    }

    /**
     * Gets the value of the text property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getText() {
      return text;
    }

    /**
     * Sets the value of the text property.
     *
     * @param value
     *          allowed object is {@link String }
     *
     */
    public void setText(final String value) {
      this.text = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="exclude" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Doc {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "id")
      protected String id;
      @XmlAttribute(name = "exclude")
      protected String exclude;

      /**
       * Gets the value of the value property.
       *
       * @return possible object is {@link String }
       *
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       *
       * @param value
       *          allowed object is {@link String }
       *
       */
      public void setValue(final String value) {
        this.value = value;
      }

      /**
       * Gets the value of the id property.
       *
       * @return possible object is {@link String }
       *
       */
      public String getId() {
        return id;
      }

      /**
       * Sets the value of the id property.
       *
       * @param value
       *          allowed object is {@link String }
       *
       */
      public void setId(final String value) {
        this.id = value;
      }

      /**
       * Gets the value of the exclude property.
       *
       * @return possible object is {@link String }
       *
       */
      public String getExclude() {
        return exclude;
      }

      /**
       * Sets the value of the exclude property.
       *
       * @param value
       *          allowed object is {@link String }
       *
       */
      public void setExclude(final String value) {
        this.exclude = value;
      }

    }

  }

}
