#!/bin/sh -e


# Source debconf library.
. /usr/share/debconf/confmodule

#start script

db_input high datafari/datafari_password || true
db_go
db_get datafari/datafari_password
sed -i -e "s/@PASSWORD@/${RET}/g" /opt/datafari/mcf/mcf_home/properties.xml
sed -i -e "s/@TEMPADMINPASSWORD@/${RET}/g" /opt/datafari/tomcat/conf/datafari.properties
sed -i -e "s/@SOLRCLOUD@/false/g" /opt/datafari/tomcat/conf/datafari.properties
chmod -R 755 /opt/datafari
id -u postgres >/dev/null 2>&1 || useradd postgres
id -u datafari >/dev/null 2>&1 || useradd datafari
chown -R datafari /opt/datafari
chown -R postgres /opt/datafari/pgsql/
chmod -R 700 /opt/datafari/pgsql/
chmod -R 777 /opt/datafari/pid
chmod -R 777 /opt/datafari/logs
chmod 755 /opt/datafari/elk/kibana/bin/*
chmod 755 /opt/datafari/elk/kibana/node/bin/*
chmod 755 /opt/datafari/elk/logstash/vendor/jruby/bin/*
chmod 755 /opt/datafari/elk/scripts/*
