#!/bin/sh -e


# Source debconf library.
. /usr/share/debconf/confmodule

#start script

db_input high datafari/node_host || true
db_go
db_get datafari/node_host
currentnodehost=${RET}

#change elk address
sed -i -e "s/localhost/${currentnodehost}/g" /opt/datafari/tomcat/conf/elk.properties
sed -i "/server.host:/c\server.host: ${currentnodehost}" /opt/datafari/elk/kibana/config/kibana.yml

sed -i -e "s/@NODEHOST@/localhost/g" /opt/datafari/tomcat/conf/datafari.properties
sed -i -e "s/@NODEHOST@/localhost/g" /opt/datafari/solr/bin/solr.in.sh
sed -i -e "s/@SOLRHOSTS@/localhost:2181/g" /opt/datafari/solr/bin/solr.in.sh
sed -i -e "s/@SOLRHOSTS@/localhost:2181/g" /opt/datafari/tomcat/conf/datafari.properties
sed -i -e "s/@ZKHOST@/localhost:2181/g" /opt/datafari/mcf/mcf_home/properties.xml


sed -i -e "s/@NUMSHARDS@/1/g" /opt/datafari/tomcat/conf/datafari.properties
sed -i -e "s/@NUMSHARDS@/1/g" /opt/datafari/bin/start-datafari.sh
sed -i -e "s/@ISMAINNODE@/true/g" /opt/datafari/tomcat/conf/datafari.properties

mkdir -p /opt/datafari/solr/solrcloud
mv /opt/datafari/solr/solr_home/FileShare /opt/datafari/solr/solrcloud
mv /opt/datafari/solr/solr_home/Statistics /opt/datafari/solr/solrcloud
mv /opt/datafari/solr/solr_home/Promolink /opt/datafari/solr/solrcloud
db_input high datafari/datafari_password || true
db_go
db_get datafari/datafari_password
chmod -R 775 /opt/datafari
export JAVA_HOME=/opt/datafari/jvm
cd /opt/datafari/mcf/mcf_home/obfuscation-utility
sed -i -e "s~@PASSWORD@~$(./obfuscate.sh ${RET})~g" /opt/datafari/mcf/mcf_home/properties-global.xml
sed -i -e "s/@TEMPADMINPASSWORD@/${RET}/g" /opt/datafari/tomcat/conf/datafari.properties
id -u postgres >/dev/null 2>&1 || useradd postgres
id -u datafari >/dev/null 2>&1 || useradd datafari
chown -R datafari /opt/datafari
chown -R postgres /opt/datafari/pgsql/
chmod -R 700 /opt/datafari/pgsql/
chmod -R 777 /opt/datafari/pid
chmod -R 777 /opt/datafari/logs
chmod 755 /opt/datafari/elk/kibana/bin/*
chmod 755 /opt/datafari/elk/kibana/node/bin/*
chmod 755 /opt/datafari/elk/logstash/vendor/jruby/bin/*
chmod 755 /opt/datafari/elk/scripts/*



