/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2015-05-20 11:33:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ResourceBundle;
import java.util.Locale;
import com.francelabs.datafari.servlets.*;

public final class capsulesConfig_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"utf-8\" />\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\n");
      out.write("\t\t<title>Capsule Configuration</title>\n");
      out.write("\t\t<link rel=\"icon\" type=\"image/png\" href=\"images/bullet.png\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main.css\" media=\"screen\" />\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/admin.css\" media=\"screen\" />\n");
      out.write("\t    <script type=\"text/javascript\" src=\"../js/jquery-1.8.1.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/menu.js\"></script>\n");
      out.write("\t</head>\n");
      out.write("\t<body class=\"gecko win\">\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\n");
      out.write("\t\n");
      out.write("\n");
      out.write("    \n");
      out.write("<br /> <br />\n");
      out.write("<div class=\"adminConfig\">\n");
 ResourceBundle resourceBundle = ResourceBundle.getBundle("com.francelabs.i18n.text", request.getLocale());
      out.write("\n");
      out.write("\n");
      out.write("\t\t<h3>");
      out.print( resourceBundle.getString("capsuleTitle") );
      out.write("</h3>\n");
      out.write("\t\t<div id=\"alertLeft\">\n");
      out.write("\t\t\t");
      out.print( resourceBundle.getString("capsuleIntro") );
      out.write("<br />\n");
      out.write("\t");
 if(request.getAttribute("errorCapsule") != null) {
      out.write("\t\n");
      out.write("\t <form method = post Action=\"Admin\">\n");
      out.write("\t <fieldset>\n");
      out.write(" \t\t<legend>");
out.print(request.getAttribute("errorCapsule").toString());
      out.write("</legend>\n");
      out.write("  \t\t\t");
      out.print( resourceBundle.getString("capsuleConfirm") );
      out.write(": <input type=\"text\"name=\"answer\"id=\"answer\" required/><br>\n");
      out.write("\t\t <input type=\"submit\" value=\"Answer\" />\n");
      out.write("\t </fieldset>\n");
      out.write("\t </form>\n");
      out.write("\t ");
 }else{ 
      out.write("\n");
      out.write("<FORM method = post Action = \"Admin\">\n");
      out.write(" <fieldset>\n");
      out.write("  ");
      out.print( resourceBundle.getString("capsuleKeyword") );
      out.write("<input type=\"text\"name=\"keyword\"id=\"keyword\" required/><br>\n");
      out.write("  ");
      out.print( resourceBundle.getString("capsuleTitle2") );
      out.write("<input type=\"text\"name=\"title\"id=\"title\" required/><br>\n");
      out.write("  ");
      out.print( resourceBundle.getString("capsuleContent") );
      out.write("<input type=\"text\"name=\"value\"id=\"value\" required/><br>\n");
      out.write("  ");
      out.print( resourceBundle.getString("capsuleDateB") );
      out.write("<input type=\"date\" name=\"dateB\" id=\"dateB\" /><br>\n");
      out.write("  ");
      out.print( resourceBundle.getString("capsuleDateE") );
      out.write("<input type=\"date\" name=\"dateE\" id=\"dateE\" /><br>\n");
      out.write("  <input type=\"submit\" value=\"Post\" />\n");
      out.write("\n");
      out.write(" </fieldset>\n");
      out.write("</FORM>\n");
} 
      out.write("\n");
      out.write(" \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
