/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2015-06-10 14:12:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ResourceBundle;
import java.util.Locale;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<title>Admin Datafari</title>\r\n");
      out.write("\t\t<meta name=\"description\" content=\"description\">\r\n");
      out.write("\t\t<meta name=\"author\" content=\"Admin Datafari\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mainbis.css\" media=\"screen\" />\r\n");
      out.write("\t\t<link href=\"../plugins/bootstrap/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"../plugins/jquery-ui/jquery-ui.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href='http://fonts.googleapis.com/css?family=Righteous' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t\t<link href=\"../plugins/fancybox/jquery.fancybox.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"../plugins/fullcalendar/fullcalendar.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"../plugins/xcharts/xcharts.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"../plugins/select2/select2.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"../plugins/justified-gallery/justifiedGallery.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"../css/style_v2.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<link href=\"../plugins/chartist/chartist.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t\t<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("\t\t<!--[if lt IE 9]>\r\n");
      out.write("\t\t\t\t<script src=\"http://getbootstrap.com/docs-assets/js/html5shiv.js\"></script>\r\n");
      out.write("\t\t\t\t<script src=\"http://getbootstrap.com/docs-assets/js/respond.min.js\"></script>\r\n");
      out.write("\t\t<![endif]-->\r\n");
      out.write("\t</head>\r\n");
      out.write("<body>\r\n");
 ResourceBundle resourceBundle = ResourceBundle.getBundle("com.francelabs.i18n.text", request.getLocale()); 
      out.write("\r\n");
      out.write("<!--Start Header-->\r\n");
      out.write("<div id=\"screensaver\">\r\n");
      out.write("\t<canvas id=\"canvas\"></canvas>\r\n");
      out.write("\t<i class=\"fa fa-lock\" id=\"screen_unlock\"></i>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"modalbox\">\r\n");
      out.write("\t<div class=\"devoops-modal\">\r\n");
      out.write("\t\t<div class=\"devoops-modal-header\">\r\n");
      out.write("\t\t\t<div class=\"modal-header-name\">\r\n");
      out.write("\t\t\t\t<span>Basic table</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"box-icons\">\r\n");
      out.write("\t\t\t\t<a class=\"close-link\">\r\n");
      out.write("\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"devoops-modal-inner\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"devoops-modal-bottom\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<header class=\"navbar\">\r\n");
      out.write("\t<div class=\"container-fluid expanded-panel\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div id=\"logo\" class=\"col-xs-12 col-sm-2\">\r\n");
      out.write("\t\t\t\t<a href=\"../index.jsp\">Datafari</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"top-panel\" class=\"col-xs-12 col-sm-10\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-8 col-sm-4\">\r\n");
      out.write("\t\t\t\t\t\t<!--  <img src=\"../images/datafari.png\" width=50% height=50% > -->\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xs-4 col-sm-8 top-panel-right\">\r\n");
      out.write("<!-- \t\t\t\t\t\t<a href=\"#\" class=\"about\">about</a> -->\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav navbar-nav pull-right panel-menu\" style=\"display:none\"><!-- when user management will be available those shall be too -->\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"index.html\" class=\"modal-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-bell\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"badge\">7</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"hidden-xs\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"ajax-link\" href=\"ajax/calendar.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-calendar\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"badge\">7</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"ajax/page_messages.html\" class=\"ajax-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"badge\">7</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle account\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"img/avatar.jpg\" class=\"img-circle\" alt=\"avatar\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<i class=\"fa fa-angle-down pull-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"user-mini pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"welcome\">Welcome,</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span>Jane Devoops</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Profile</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"ajax/page_messages.html\" class=\"ajax-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Messages</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"ajax/gallery_simple.html\" class=\"ajax-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-picture-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Albums</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"ajax/calendar.html\" class=\"ajax-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-tasks\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Tasks</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-cog\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Settings</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-power-off\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span>Logout</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("<!--End Header-->\r\n");
      out.write("<!--Start Container-->\r\n");
      out.write("<div id=\"main\" class=\"container-fluid\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div id=\"sidebar-left\" class=\"col-xs-2 col-sm-2\">\r\n");
      out.write("\t\t\t<ul class=\"nav main-menu\">\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"../ajax/dashboard.html\" class=\"ajax-link\"> <i -->\r\n");
      out.write("<!-- \t\t\t\t\t\t\tclass=\"fa fa-dashboard\"></i> <span class=\"hidden-xs\">Dashboard</span> -->\r\n");
      out.write("\t\t\t\t\t</a> <a href=\"../ajax/manifoldcf.html\" class=\"ajax-link\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-bar-chart-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"hidden-xs\">");
      out.print( resourceBundle.getString("connectors"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-table\"></i>\r\n");
      out.write("\t\t\t\t\t\t <span class=\"hidden-xs\">");
      out.print( resourceBundle.getString("statistics"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/usageStatistics.html\">Usage statistics</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/corpusStatistics.html\">Corpus statistics</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/systemStatistics.html\">System statistics</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa \t\"></i>\r\n");
      out.write("\t\t\t\t\t\t <span class=\"hidden-xs\">");
      out.print( resourceBundle.getString("admin"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/solr.html\">");
      out.print( resourceBundle.getString("solrAdmin"));
      out.write("</a></li>\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/forms_layouts.html\">Layouts</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/forms_file_uploader.html\">File Uploader</a></li> -->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-desktop\"></i>\r\n");
      out.write("\t\t\t\t\t\t <span class=\"hidden-xs\">");
      out.print( resourceBundle.getString("conf"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/Capsules.html\">");
      out.print( resourceBundle.getString("capsules"));
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/Synonyms.html\">");
      out.print( resourceBundle.getString("synonyms"));
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/StopWords.html\">");
      out.print( resourceBundle.getString("stopwords"));
      out.write("</a></li>\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/ui_jquery-ui.html\">Query based boots</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/ui_icons.html\">Document based boosts</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/ui_icons.html\">OCR: On/Off</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/ui_icons.html\">Duplicate identifiers</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/ui_icons.html\">User Management</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/ui_icons.html\">Autocomplete configuration</a></li> -->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("<!-- \t\t\t\t<li class=\"dropdown\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<i class=\"fa fa-map-marker\"></i> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<span class=\"hidden-xs\">Search engine users</span> -->\r\n");
      out.write("<!-- \t\t\t\t\t</a> -->\r\n");
      out.write("<!-- \t\t\t\t\t<ul class=\"dropdown-menu\"> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/maps.html\">Save search queries</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/Alerts.html\">Create alerts</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/map_leaflet.html\">Favorite documents</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t\t</li> -->\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-picture-o\"></i>\r\n");
      out.write("\t\t\t\t\t\t <span class=\"hidden-xs\">");
      out.print( resourceBundle.getString("servers"));
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/Tomcat.html\">Tomcat</a></li>\r\n");
      out.write("<!-- \t\t\t\t\t\t<li><a class=\"ajax-link\" href=\"../ajax/Jetty.html\">Jetty</a></li> -->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--Start Content-->\r\n");
      out.write("\t\t<div id=\"content\" class=\"col-xs-12 col-sm-10\">\r\n");
      out.write("\t\t\t<div id=\"about\">\r\n");
      out.write("\t\t\t\t<div class=\"about-inner\">\r\n");
      out.write("\t\t\t\t\t<h4 class=\"page-header\">Open-source admin theme for you</h4>\r\n");
      out.write("\t\t\t\t\t<p>DevOOPS team</p>\r\n");
      out.write("\t\t\t\t\t<p>Homepage - <a href=\"http://devoops.me\" target=\"_blank\">http://devoops.me</a></p>\r\n");
      out.write("\t\t\t\t\t<p>Email - <a href=\"mailto:devoopsme@gmail.com\">devoopsme@gmail.com</a></p>\r\n");
      out.write("\t\t\t\t\t<p>Twitter - <a href=\"http://twitter.com/devoopsme\" target=\"_blank\">http://twitter.com/devoopsme</a></p>\r\n");
      out.write("\t\t\t\t\t<p>Donate - BTC 123Ci1ZFK5V7gyLsyVU36yPNWSB5TDqKn3</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"ajax-content\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--End Content-->\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("</script>\r\n");
      out.write("<!--End Container-->\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("<!--<script src=\"http://code.jquery.com/jquery.js\"></script>-->\r\n");
      out.write("<script src=\"../plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"../plugins/jquery-ui/jquery-ui.min.js\"></script>\r\n");
      out.write("<script src=\"./i18nInit.js\"></script>\r\n");
      out.write("<script src=\"./../js/AjaxFranceLabs/i18njs.js\"></script>\r\n");
      out.write("<!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("<script src=\"../plugins/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../plugins/justified-gallery/jquery.justifiedGallery.min.js\"></script>\r\n");
      out.write("<script src=\"../plugins/tinymce/tinymce.min.js\"></script>\r\n");
      out.write("<script src=\"../plugins/tinymce/jquery.tinymce.min.js\"></script>\r\n");
      out.write("<!-- All functions for this theme + document.ready processing -->\r\n");
      out.write("<script src=\"../js/devoops.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
