/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2015-05-12 13:02:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\t<div id=\"menu\">\n");
      out.write("\t<ul id=\"sddm\">\n");
      out.write("    <li><a href=\"#\" \n");
      out.write("        onmouseover=\"mopen('m1')\" \n");
      out.write("        onmouseout=\"mclosetime()\">Search Engine</a>\n");
      out.write("        <div id=\"m1\" \n");
      out.write("            onmouseover=\"mcancelclosetime()\" \n");
      out.write("            onmouseout=\"mclosetime()\">\n");
      out.write("        <a href=\"solr.jsp\">Solr Admin</a>\n");
      out.write("\t\t<a href=\"banana.jsp\">Graphical Stats</a>\n");
      out.write("        <a href=\"stats.jsp\">Stats</a>\n");
      out.write("\t\t<a href=\"capsulesConfig.jsp\">Capsules</a>\n");
      out.write("\t\t<a href=\"synonymConfig.jsp\">Synonyms</a>\n");
      out.write("\t\t<a href=\"stopWordsConfig.jsp\">StopWords</a>\n");
      out.write("\t\t<a href=\"alertsConfig.jsp\">Alerts</a>\n");
      out.write("        </div>\n");
      out.write("    </li>\n");
      out.write("    <li><a href=\"#\" \n");
      out.write("        onmouseover=\"mopen('m2')\" \n");
      out.write("        onmouseout=\"mclosetime()\">Crawler</a>\n");
      out.write("        <div id=\"m2\" \n");
      out.write("            onmouseover=\"mcancelclosetime()\" \n");
      out.write("            onmouseout=\"mclosetime()\">\n");
      out.write("        <a href=\"manifoldcf.jsp\">ManifoldCF Admin</a>\n");
      out.write("        </div>\n");
      out.write("    </li>\n");
      out.write("    <li><a href=\"#\" \n");
      out.write("        onmouseover=\"mopen('m3')\" \n");
      out.write("        onmouseout=\"mclosetime()\">Server</a>\n");
      out.write("        <div id=\"m3\" \n");
      out.write("            onmouseover=\"mcancelclosetime()\" \n");
      out.write("            onmouseout=\"mclosetime()\">\n");
      out.write("        <a href=\"tomcat.jsp\">Tomcat</a>\n");
      out.write("        </div>\n");
      out.write("    </li>\n");
      out.write("    <!-- \n");
      out.write("    <li><a href=\"#\">Order</a></li>\n");
      out.write("    <li><a href=\"#\">Help</a></li>\n");
      out.write("    <li><a href=\"#\">Contact</a></li> -->\n");
      out.write("</ul>\n");
      out.write("</div>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
