/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2015-05-21 08:40:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class stats_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("<title>Statistiques</title>\r\n");
      out.write("\r\n");
      out.write("\t\t<link rel=\"icon\" type=\"image/png\" href=\"images/bullet.png\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main.css\" media=\"screen\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/admin.css\" media=\"screen\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/results.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/checkbox.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/flexigrid.pack.css\" />\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"../js/jquery-1.8.1.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/menu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"gecko win\">\r\n");
      out.write(" \r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/jquery-1.8.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/function/empty.func.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/jquery-ui-1.8.23.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/jquery.columnizer.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/AjaxFranceLabs/i18njs.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/AjaxFranceLabs/uuid.core.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/AjaxFranceLabs/core/Core.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/core/AbstractModule.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/core/AbstractWidget.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/core/AbstractFacetWidget.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/core/Parameter.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/core/ParameterStore.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/core/AbstractManager.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/manager/Manager.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/modules/Pager.module.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/modules/Autocomplete.module.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/widgets/ResultStats.widget.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/widgets/StatsQuery.widget.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/widgets/StatsInformation.widget.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/widgets/Table.widget.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/widgets/TableFacetQueriesWidget.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/widgets/Capsule.widget.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"../js/AjaxFranceLabs/widgets/Spellchecker.widget.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/stats.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/flexigrid.pack.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"../js/menu.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("<div id=\"solr\">\r\n");
      out.write("\t\t<div id=\"searchBar\"></div>\r\n");
      out.write("\t\t<div id=\"result_information\"></div>\r\n");
      out.write("\t\t<div id=\"results\"></div>\t\t\t\r\n");
      out.write("\t\t<div class=\"clear\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
