/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2015-05-12 12:51:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ResourceBundle;
import java.util.Locale;

public final class synonymConfig_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />\r\n");
      out.write("\t\t<title>Synonym Configuration</title>\r\n");
      out.write("\t\t<link rel=\"icon\" type=\"image/png\" href=\"images/bullet.png\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/main.css\" media=\"screen\" />\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/admin.css\" media=\"screen\" />\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"../js/jquery-1.8.1.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/menu.js\"></script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body class=\"gecko win\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<br /> <br />\r\n");
      out.write("<div class=\"adminConfig\">\r\n");
 ResourceBundle resourceBundle = ResourceBundle.getBundle("com.francelabs.i18n.text", request.getLocale()); 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<h3>");
      out.print( resourceBundle.getString("synonymTitle") );
      out.write("</h3>\r\n");
      out.write("<div id=\"synonymLeft\">\r\n");
      out.print( resourceBundle.getString("synonymIntro") );
      out.write("<br/><br/>\r\n");
      out.print( resourceBundle.getString("synonymTechno") );
      out.write("<br/><br/>\r\n");
      out.print( resourceBundle.getString("synonymHelp") );
      out.write("<br/><br/>\r\n");
      out.write("\r\n");
      out.write("<form action=\"synonyms.jsp\" method=\"post\"\r\n");
      out.write("                        enctype=\"multipart/form-data\">\r\n");
      out.write("<input type=\"file\" name=\"file\" size=\"30\" />\r\n");
      out.write("<br />\r\n");
      out.write("<input type=\"submit\" value=\"");
      out.print( resourceBundle.getString("synonymSend") );
      out.write("\" id=\"submitSynonyms\" />\r\n");
      out.print( resourceBundle.getString("synonymSelection") );
      out.write("\r\n");
      out.write("</form><br /><br />\r\n");
      out.write("\r\n");
      out.write("<form action=\"download.jsp\">\r\n");
      out.write("    <input type=\"submit\" value=\"");
      out.print( resourceBundle.getString("synonymDownloadButton") );
      out.write("\" id=\"downloadSynonyms\" >\r\n");
      out.write("    ");
      out.print( resourceBundle.getString("synonymDownload") );
      out.write(" <br/>\r\n");
      out.write("</form> \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
