function internationalize() {
  // Internationalize content
  $("#topbar1").text(window.i18n.msgStore['home']);
  $("#topbar2").text(window.i18n.msgStore['adminUI-aiMenu']);
  $("#topbar3").text(window.i18n.msgStore['adminUI-ragConf']);

//  $("#enableRagLabel").text(window.i18n.msgStore['ragConf-enableRagLabel']);
//  $("#enableAgenticLabel").text(window.i18n.msgStore['ragConf-enableAgenticLabel']);
//  $("#enableSummarizationLabel").text(window.i18n.msgStore['ragConf-enableSummarizationLabel']);
//  $("#enableSynthesisLabel").text(window.i18n.msgStore['ragConf-enableSynthesisLabel']);
  $("#ragTopKLabel").text(window.i18n.msgStore['ragConf-ragTopKLabel']);
  $("#rrfTopKLabel").text(window.i18n.msgStore['ragConf-rrfTopKLabel']);
  $("#rrfRankConstantLabel").text(window.i18n.msgStore['ragConf-rrfRankConstantLabel']);
  $("#solrEmbeddingsModelLabel").text(window.i18n.msgStore['ragConf-solrEmbeddingsModelLabel']);
  $("#ragOperatorLabel").text(window.i18n.msgStore['ragConf-ragOperatorLabel']);
  $("#chunkingMaxFilesLabel").text(window.i18n.msgStore['ragConf-chunkingMaxFilesLabel']);
  $("#retrievalMethodLabel").text(window.i18n.msgStore['ragConf-retrievalMethodLabel']);
  $("#chatMemoryHistorySizeLabel").text(window.i18n.msgStore['ragConf-chatMemoryHistorySizeLabel']);
  $("#chatMemoryEnabledLabel").text(window.i18n.msgStore['ragConf-chatMemoryEnabledLabel']);
  $("#chatQueryRewritingEnabledLabel").text(window.i18n.msgStore['ragConf-chatQueryRewritingEnabledLabel']);
  $("#chatQueryRewritingEnabledBM25Label").text(window.i18n.msgStore['ragConf-chatQueryRewritingEnabledBM25Label']);
  $("#chatQueryRewritingEnabledVectorLabel").text(window.i18n.msgStore['ragConf-chatQueryRewritingEnabledVectorLabel']);
  $("#chunkingChunkSizeLabel").text(window.i18n.msgStore['ragConf-chunkingChunkSizeLabel']);
  $("#maxRequestSizeLabel").text(window.i18n.msgStore['ragConf-maxRequestSizeLabel']);
  $("#chunkingStrategyLabel").text(window.i18n.msgStore['ragConf-chunkingStrategyLabel']);
  $("#enableLoopControlLabel").text(window.i18n.msgStore['ragConf-enableLoopControlLabel']);
  $("#ragServiceLegend").text(window.i18n.msgStore['ragConf-ragServiceLegend']);
  $("#agenticServiceLegend").text(window.i18n.msgStore['ragConf-agenticServiceLegend']);
  $("#aiServicesLegend").text(window.i18n.msgStore['ragConf-aiServicesLegend']);

  $('#enableLoopControlLabel')
      .append(
          "<span><button type='button' class='btn btn-secondary tooltips' data-toggle='tooltip' data-placement='right' title=" +
          "'When Loop Control is enabled, responses generated by an agent must be rated with a score of {threshold} or higher. It the test fails, the response is re-generated. There cannot be more than {max_iterations} iterations.'" +
          ">i</button></span>");
  $('#loopControlMaxIterationsBeforeSecondaryLabel')
      .append(
          "<span><button type='button' class='btn btn-secondary tooltips' data-toggle='tooltip' data-placement='right' title='If the secondary threshold is enabled, the minimal score to reach for a generated response is lowered to {secondary_threshold}, starting at the {secondary_starting_iterations}th iteration.'>i</button></span>");

}

function loadRagConfig() {
  $.get("../rest/v2.0/management/ragConfig", function (data) {

    $('#chunkingStrategy').val(data.chunkingStrategy || 'refine');
    $('#maxRequestSize').val(data.maxRequestSize || 40000);

    $('#chunkingMaxFiles').val(data.chunkingMaxFiles || 3);
    $('#chunkingChunkSize').val(data.chunkingChunkSize || 3000);
    $('#ragOperator').val(data.ragOperator || 'OR');

    $('#chatQueryRewritingEnabledBM25').prop('checked', data.chatQueryRewritingEnabledBM25 === true).change();
    $('#chatQueryRewritingEnabledVector').prop('checked', data.chatQueryRewritingEnabledVector === true).change();
    $('#chatMemoryEnabled').prop('checked', data.chatMemoryEnabled === true).change();
    $('#chatMemoryHistorySize').val(data.chatMemoryHistorySize || 6);

    $('#enableLoopControl').prop('checked', data.enableLoopControl === true).change();
    updateLoopControlOnlyVisibility();
    $('#loopControlMaxIterations').val(data.loopControlMaxIterations || 3);
    $('#loopControlMinScore').val(data.loopControlMinScore || 0.8);
    $('#loopControlMaxIterationsBeforeSecondary').val(data.loopControlMaxIterationsBeforeSecondary || 3);
    $('#loopControlMinScoreSecondary').val(data.loopControlMinScoreSecondary || 0.6);

    $('#retrievalMethod').val(data.retrievalMethod || "bm25");
    updateRetrievalVisibility();
    $('#ragTopK').val(data.ragTopK || 10);
    $('#rrfTopK').val(data.rrfTopK || 50);
    $('#rrfRankConstant').val(data.rrfRankConstant || 60);

  }, "json");
}


// Display retrieval-related fields according to the selected method
function updateRetrievalVisibility() {
  const value = $('#retrievalMethod').val();

  if (value === "vector") {
    $('.bm25Only').hide();
    $('.rrfOnly').hide();
    $('.vectorSearchOnly').show();
  } else if (value === "rrf") {
    $('.bm25Only').hide();
    $('.vectorSearchOnly').hide();
    $('.rrfOnly').show();
  } else {
    $('.rrfOnly').hide();
    $('.vectorSearchOnly').hide();
    $('.bm25Only').show();
  }
}

// If Loop Control is disabled, hide associated fields
function updateLoopControlOnlyVisibility() {
  const value = $('#enableLoopControl').is(':checked');

  if (value === true) {
    $('.loopControlOnly').show();
  } else {
    $('.loopControlOnly').hide();
  }
}

function submitRagConfig(event) {
  event.preventDefault();

  if (!$('#ragConf-form')[0].checkValidity()) {
    $('#ragConf-form').addClass('was-validated');
    return;
  }

  $('#save-conf').prop('disabled', true);
  $('#loadingIndicator').show();

  const payload = {
//    "ai.enable.rag": $('#enableRag').is(':checked'),
//    "ai.enable.agentic": $('#enableAgentic').is(':checked'),
//    "ai.enable.summarization": $('#enableSummarization').is(':checked'),
//    "ai.enable.synthesis": $('#enableSynthesis').is(':checked'),
    "prompt.chunking.strategy": $('#chunkingStrategy').val(),
    "prompt.max.request.size": $('#maxRequestSize').val(),
    "chunking.maxFiles": $('#chunkingMaxFiles').val(),
    "chunking.chunk.size": $('#chunkingChunkSize').val(),
    "rag.operator": $('#ragOperator').val(),
    "chat.query.rewriting.enabled.bm25": $('#chatQueryRewritingEnabledBM25').is(':checked'),
    "chat.query.rewriting.enabled.vector": $('#chatQueryRewritingEnabledVector').is(':checked'),
    "chat.memory.enabled": $('#chatMemoryEnabled').is(':checked'),
    "chat.memory.history.size": $('#chatMemoryHistorySize').val(),
    "rag.topK": $('#ragTopK').val(),
    "rrf.topK": $('#rrfTopK').val(),
    "rrf.rank.constant": $('#rrfRankConstant').val(),
    "retrieval.method": $('#retrievalMethod').val(),
    "agentic.enable.loop.control": $('#enableLoopControl').is(':checked'),
    "agentic.loop.control.max.iterations": $('#loopControlMaxIterations').val(),
    "agentic.loop.control.min.score": $('#loopControlMinScore').val(),
    "agentic.loop.control.max.iterations.secondary": $('#loopControlMaxIterationsBeforeSecondary').val(),
    "agentic.loop.control.min.score.secondary": $('#loopControlMinScoreSecondary').val(),
  };

  $.ajax({
    url: "../rest/v2.0/management/ragConfig",
    type: "POST",
    contentType: "application/json",
    data: JSON.stringify(payload),
    success: function () {
      $('#message')
        .removeClass('alert-danger')
        .addClass('alert-success')
        .text("Configuration saved successfully")
        .show();
      setTimeout(() => $('#message').fadeOut(), 3000);
    },
    error: function () {
      $('#message')
        .removeClass('alert-success')
        .addClass('alert-danger')
        .text("An error occurred while saving configuration.")
        .show();
    },
    complete: function () {
      $('#save-conf').prop('disabled', false);
      $('#loadingIndicator').hide();
    }
  });
}

$(document).ready(function () {
  internationalize();
  loadRagConfig();

  $('#chatMemoryEnabled').bootstrapToggle();
  $('#chatQueryRewritingEnabledBM25').bootstrapToggle();
  $('#chatQueryRewritingEnabledVector').bootstrapToggle();
  $('#enableLoopControl').bootstrapToggle();
  $('#retrievalMethod').on('change', updateRetrievalVisibility);
  $('#enableLoopControl').on('change', updateLoopControlOnlyVisibility);

  $('#ragConf-form').on('submit', submitRagConfig);
});