/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2015-04-07 13:29:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.manifoldcf.core.interfaces.*;
import org.apache.manifoldcf.ui.i18n.*;
import org.apache.manifoldcf.agents.interfaces.*;
import org.apache.manifoldcf.authorities.interfaces.*;
import org.apache.manifoldcf.crawler.interfaces.*;
import java.util.*;

public final class navigation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/jsp/x.tld", Long.valueOf(1428407612000L));
    _jspx_dependants.put("/WEB-INF/jsp/c.tld", Long.valueOf(1428407612000L));
    _jspx_dependants.put("/WEB-INF/jsp/sql.tld", Long.valueOf(1428407612000L));
    _jspx_dependants.put("/WEB-INF/jsp/fmt.tld", Long.valueOf(1428407612000L));
    _jspx_dependants.put("/adminDefaults.jsp", Long.valueOf(1428407612000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


/* $Id: adminDefaults.jsp 1601529 2014-06-09 23:19:08Z kwright $ */

/**
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements. See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License. You may obtain a copy of the License at
* 
* http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

      out.write("\r\n");
      out.write("\r\n");
      org.apache.manifoldcf.ui.beans.ThreadContext thread = null;
      thread = (org.apache.manifoldcf.ui.beans.ThreadContext) _jspx_page_context.getAttribute("thread", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (thread == null){
        thread = new org.apache.manifoldcf.ui.beans.ThreadContext();
        _jspx_page_context.setAttribute("thread", thread, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.manifoldcf.ui.beans.AdminProfile adminprofile = null;
      synchronized (session) {
        adminprofile = (org.apache.manifoldcf.ui.beans.AdminProfile) _jspx_page_context.getAttribute("adminprofile", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (adminprofile == null){
          adminprofile = new org.apache.manifoldcf.ui.beans.AdminProfile();
          _jspx_page_context.setAttribute("adminprofile", adminprofile, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	IThreadContext threadContext = thread.getThreadContext();
	org.apache.manifoldcf.ui.multipart.MultipartWrapper variableContext = (org.apache.manifoldcf.ui.multipart.MultipartWrapper)threadContext.get("__WRAPPER__");
	if (variableContext == null)
	{
		variableContext = new org.apache.manifoldcf.ui.multipart.MultipartWrapper(request,adminprofile);
		threadContext.save("__WRAPPER__",variableContext);
	}

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");


/* $Id: navigation.jsp 1601529 2014-06-09 23:19:08Z kwright $ */

/**
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements. See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License. You may obtain a copy of the License at
* 
* http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

      out.write("\r\n");
      out.write("\r\n");

	// This module is meant to be called within a table cell, and will drop the
	// lcf navigation into the cell


      out.write("\r\n");
      out.write("\r\n");
      out.write("<p class=\"menumain\"><nobr>");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.Outputs"));
      out.write("</nobr></p>\r\n");
      out.write("<ul class=\"menusecond\">\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"listtransformations.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Listtransformationconnections"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.ListTransformationConnections"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"listoutputs.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Listoutputconnections"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.ListOutputConnections"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<p class=\"menumain\"><nobr>");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.Authorities"));
      out.write("</nobr></p>\r\n");
      out.write("<ul class=\"menusecond\">\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"listgroups.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Listauthoritygroups"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.ListAuthorityGroups"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"listmappers.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Listusermappings"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.ListUserMappings"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"listauthorities.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Listauthorities"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.ListAuthorityConnections"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<p class=\"menumain\"><nobr>");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.Repositories"));
      out.write("</nobr></p>\r\n");
      out.write("<ul class=\"menusecond\">\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"listconnections.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Listrepositoryconnections"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.ListRepositoryConnections"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<p class=\"menumain\"><nobr>");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.Jobs"));
      out.write("</nobr></p>\r\n");
      out.write("<ul class=\"menusecond\">\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"listjobs.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Listjobs"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.ListAllJobs"));
      out.write("</a></nobr>\t\t\t\t\t\t\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"showjobstatus.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Managejobs"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.StatusAndJobManagement"));
      out.write("</a></nobr>\t\t\t\t\t\t\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<p class=\"menumain\"><nobr>");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.StatusReports"));
      out.write("</nobr></p>\r\n");
      out.write("<ul class=\"menusecond\">\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"documentstatus.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Documentstatus"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.DocumentStatus"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"queuestatus.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Queuestatus"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.QueueStatus"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<p class=\"menumain\"><nobr>");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.HistoryReports"));
      out.write("</nobr></p>\r\n");
      out.write("<ul class=\"menusecond\">\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"simplereport.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Simplehistory"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.SimpleHistory"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"maxactivityreport.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Maximumactivity"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.MaximumActivity"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"maxbandwidthreport.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Maximumbandwidth"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.MaximumBandwidth"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"resultreport.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Resulthistogram"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.ResultHistogram"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\r\n");
      out.write("<p class=\"menumain\"><nobr>");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.Miscellaneous"));
      out.write("</nobr></p>\r\n");
      out.write("<ul class=\"menusecond\">\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href='");
      out.print("http://manifoldcf.apache.org/release/trunk/"+Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.Locale")+"/end-user-documentation.html");
      out.write("' alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.Help"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.Help"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li class=\"menuitem\">\r\n");
      out.write("\t\t<nobr><a class=\"menulink\" href=\"logout.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"navigation.LogOut"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"navigation.LogOut"));
      out.write("</a></nobr>\r\n");
      out.write("\t</li>\r\n");
      out.write("</ul>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
