/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.40
 * Generated at: 2015-04-07 13:47:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.manifoldcf.core.interfaces.*;
import org.apache.manifoldcf.core.util.*;
import org.apache.manifoldcf.ui.i18n.*;
import org.apache.manifoldcf.agents.interfaces.*;
import org.apache.manifoldcf.crawler.interfaces.*;
import org.apache.manifoldcf.authorities.interfaces.*;
import java.util.*;

public final class showjobstatus_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/jsp/x.tld", Long.valueOf(1428407612000L));
    _jspx_dependants.put("/adminHeaders.jsp", Long.valueOf(1428407612000L));
    _jspx_dependants.put("/WEB-INF/jsp/c.tld", Long.valueOf(1428407612000L));
    _jspx_dependants.put("/WEB-INF/jsp/sql.tld", Long.valueOf(1428407612000L));
    _jspx_dependants.put("/WEB-INF/jsp/fmt.tld", Long.valueOf(1428407612000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 response.setHeader("Pragma","No-cache");
response.setDateHeader("Expires",0);
response.setHeader("Cache-Control", "no-cache");
response.setDateHeader("max-age", 0);
response.setContentType("text/html;charset=utf-8");

      out.write("\r\n");
      out.write("\r\n");


/* $Id: adminHeaders.jsp 1601529 2014-06-09 23:19:08Z kwright $ */

/**
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements. See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License. You may obtain a copy of the License at
* 
* http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.manifoldcf.ui.beans.ThreadContext thread = null;
      thread = (org.apache.manifoldcf.ui.beans.ThreadContext) _jspx_page_context.getAttribute("thread", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (thread == null){
        thread = new org.apache.manifoldcf.ui.beans.ThreadContext();
        _jspx_page_context.setAttribute("thread", thread, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      org.apache.manifoldcf.ui.beans.AdminProfile adminprofile = null;
      synchronized (session) {
        adminprofile = (org.apache.manifoldcf.ui.beans.AdminProfile) _jspx_page_context.getAttribute("adminprofile", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (adminprofile == null){
          adminprofile = new org.apache.manifoldcf.ui.beans.AdminProfile();
          _jspx_page_context.setAttribute("adminprofile", adminprofile, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	if (adminprofile.getLoggedOn() == false)
	{
		response.sendRedirect("login.jsp");
		return;
	}

	IThreadContext threadContext = thread.getThreadContext();
	org.apache.manifoldcf.ui.multipart.MultipartWrapper variableContext = (org.apache.manifoldcf.ui.multipart.MultipartWrapper)threadContext.get("__WRAPPER__");
	if (variableContext == null)
	{
		variableContext = new org.apache.manifoldcf.ui.multipart.MultipartWrapper(request,adminprofile);
		threadContext.save("__WRAPPER__",variableContext);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


/* $Id: showjobstatus.jsp 1601529 2014-06-09 23:19:08Z kwright $ */

/**
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements. See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License. You may obtain a copy of the License at
* 
* http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
boolean maintenanceUnderway = org.apache.manifoldcf.crawler.system.ManifoldCF.checkMaintenanceUnderway();


      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<link rel=\"StyleSheet\" href=\"style.css\" type=\"text/css\" media=\"screen\"/>\r\n");
      out.write("\t<title>\r\n");
      out.write("\t\t");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.ApacheManifoldCFStatusOfAllJobs"));
      out.write("\r\n");
      out.write("\t</title>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\r\n");
      out.write("\tfunction Start(jobID)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.liststatuses.op.value=\"Start\";\r\n");
      out.write("\t\tdocument.liststatuses.jobid.value=jobID;\r\n");
      out.write("\t\tdocument.liststatuses.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction StartMinimal(jobID)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.liststatuses.op.value=\"StartMinimal\";\r\n");
      out.write("\t\tdocument.liststatuses.jobid.value=jobID;\r\n");
      out.write("\t\tdocument.liststatuses.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction Abort(jobID)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.liststatuses.op.value=\"Abort\";\r\n");
      out.write("\t\tdocument.liststatuses.jobid.value=jobID;\r\n");
      out.write("\t\tdocument.liststatuses.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction Restart(jobID)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.liststatuses.op.value=\"Restart\";\r\n");
      out.write("\t\tdocument.liststatuses.jobid.value=jobID;\r\n");
      out.write("\t\tdocument.liststatuses.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction RestartMinimal(jobID)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.liststatuses.op.value=\"RestartMinimal\";\r\n");
      out.write("\t\tdocument.liststatuses.jobid.value=jobID;\r\n");
      out.write("\t\tdocument.liststatuses.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction Pause(jobID)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.liststatuses.op.value=\"Pause\";\r\n");
      out.write("\t\tdocument.liststatuses.jobid.value=jobID;\r\n");
      out.write("\t\tdocument.liststatuses.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction Resume(jobID)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdocument.liststatuses.op.value=\"Resume\";\r\n");
      out.write("\t\tdocument.liststatuses.jobid.value=jobID;\r\n");
      out.write("\t\tdocument.liststatuses.submit();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//-->\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"standardbody\">\r\n");
      out.write("\r\n");
      out.write("    <table class=\"page\">\r\n");
      out.write("      <tr><td colspan=\"2\" class=\"banner\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "banner.jsp", out, true);
      out.write("</td></tr>\r\n");
      out.write("      <tr><td class=\"navigation\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "navigation.jsp", out, true);
      out.write("</td>\r\n");
      out.write("       <td class=\"window\">\r\n");
      out.write("\t<p class=\"windowtitle\">");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.StatusOfJobs"));
      out.write("</p>\r\n");

if (maintenanceUnderway == false)
{

      out.write("\r\n");
      out.write("\t<form class=\"standardform\" name=\"liststatuses\" action=\"execute.jsp\" method=\"POST\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"op\" value=\"Continue\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"type\" value=\"jobstatus\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"jobid\" value=\"\"/>\r\n");
      out.write("\r\n");

    try
    {
	// Get the max count
	int maxCount = LockManagerFactory.getIntProperty(threadContext,"org.apache.manifoldcf.ui.maxstatuscount",500000);
	// Get the job manager handle
	IJobManager manager = JobManagerFactory.make(threadContext);
	JobStatus[] jobs = manager.getAllStatus(true,maxCount);

      out.write("\r\n");
      out.write("\t\t<table class=\"datatable\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"separator\" colspan=\"8\"><hr/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr class=\"headerrow\">\r\n");
      out.write("\t\t\t\t<td class=\"columnheader\"></td><td class=\"columnheader\">");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Name"));
      out.write("</td><td class=\"columnheader\">");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Status"));
      out.write("</td><td class=\"columnheader\">");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.StartTime"));
      out.write("</td><td class=\"columnheader\">");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.EndTime"));
      out.write("</td><td class=\"columnheader\">");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Documents"));
      out.write("</td><td class=\"columnheader\">");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Active"));
      out.write("</td><td class=\"columnheader\">");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Processed"));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");

	int i = 0;
	while (i < jobs.length)
	{
		JobStatus js = jobs[i++];
		String statusName;
		int status = js.getStatus();
		switch (status)
		{
		case JobStatus.JOBSTATUS_NOTYETRUN:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Notyetrun");
			break;
		case JobStatus.JOBSTATUS_RUNNING:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Running");
			break;
		case JobStatus.JOBSTATUS_RUNNING_UNINSTALLED:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Runningnoconnector");
			break;
		case JobStatus.JOBSTATUS_ABORTING:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Aborting");
			break;
		case JobStatus.JOBSTATUS_RESTARTING:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Restarting");
			break;
		case JobStatus.JOBSTATUS_STOPPING:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Stopping");
			break;
		case JobStatus.JOBSTATUS_RESUMING:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Resuming");
			break;
		case JobStatus.JOBSTATUS_PAUSED:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Paused");
			break;
		case JobStatus.JOBSTATUS_COMPLETED:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Done");
			break;
		case JobStatus.JOBSTATUS_WINDOWWAIT:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Waiting");
			break;
		case JobStatus.JOBSTATUS_STARTING:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Startingup");
			break;
		case JobStatus.JOBSTATUS_DESTRUCTING:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Cleaningup");
			break;
		case JobStatus.JOBSTATUS_JOBENDCLEANUP:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Terminating");
			break;
		case JobStatus.JOBSTATUS_JOBENDNOTIFICATION:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Endnotification");
			break;
		case JobStatus.JOBSTATUS_ERROR:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.ErrorColon")+" "+js.getErrorText();
			break;
		default:
			statusName = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Unknown");
			break;
		}
		String startTime = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Notstarted");
		if (js.getStartTime() != -1L)
			startTime = new Date(js.getStartTime()).toString();
		String endTime = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Aborted");
		if (js.getStartTime() == -1L)
			endTime = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Neverrun");
		else
		{
			if (js.getEndTime() == -1L)
			{
				if (status == JobStatus.JOBSTATUS_COMPLETED)
					endTime = Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Aborted");
				else
					endTime = "";
			}
			else
				endTime = new Date(js.getEndTime()).toString();
		}

      out.write("\r\n");
      out.write("\t\t<tr ");
      out.print("class=\""+((i%2==0)?"evendatarow":"odddatarow")+"\"");
      out.write(">\r\n");
      out.write("\t\t\t<td class=\"columncell\">\r\n");
      out.write("\t\t\t\t<nobr>\r\n");

		if (status == JobStatus.JOBSTATUS_NOTYETRUN ||
			status == JobStatus.JOBSTATUS_COMPLETED ||
			status == JobStatus.JOBSTATUS_ERROR)
		{

      out.write("\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print("javascript:Start(\""+js.getJobID()+"\")");
      out.write("' alt='");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"showjobstatus.Startjob")+" "+js.getJobID());
      out.write('\'');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Start"));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print("javascript:StartMinimal(\""+js.getJobID()+"\")");
      out.write("' alt='");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"showjobstatus.Startjob")+" "+js.getJobID()+" "+Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.minimally"));
      out.write('\'');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Startminimal"));
      out.write("</a>\r\n");

		}
		if (status == JobStatus.JOBSTATUS_RUNNING ||
			status == JobStatus.JOBSTATUS_RUNNING_UNINSTALLED ||
			status == JobStatus.JOBSTATUS_WINDOWWAIT ||
			status == JobStatus.JOBSTATUS_PAUSED ||
			status == JobStatus.JOBSTATUS_STARTING)
		{

      out.write("\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print("javascript:Restart(\""+js.getJobID()+"\")");
      out.write("' alt='");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"showjobstatus.Restartjob")+" "+js.getJobID());
      out.write('\'');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Restart"));
      out.write("</a>\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print("javascript:RestartMinimal(\""+js.getJobID()+"\")");
      out.write("' alt='");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"showjobstatus.Restartjob")+" "+js.getJobID()+" "+Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.minimally"));
      out.write('\'');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Restartminimal"));
      out.write("</a>\r\n");

		}
		if (status == JobStatus.JOBSTATUS_RUNNING ||
			status == JobStatus.JOBSTATUS_RUNNING_UNINSTALLED ||
			status == JobStatus.JOBSTATUS_WINDOWWAIT)
		{

      out.write("\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print("javascript:Pause(\""+js.getJobID()+"\")");
      out.write("' alt='");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"showjobstatus.Pausejob")+" "+js.getJobID());
      out.write('\'');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Pause"));
      out.write("</a>\r\n");

		}
		if (status == JobStatus.JOBSTATUS_RUNNING ||
			status == JobStatus.JOBSTATUS_RUNNING_UNINSTALLED ||
			status == JobStatus.JOBSTATUS_STOPPING ||
			status == JobStatus.JOBSTATUS_RESUMING ||
			status == JobStatus.JOBSTATUS_WINDOWWAIT ||
			status == JobStatus.JOBSTATUS_PAUSED ||
			status == JobStatus.JOBSTATUS_STARTING ||
			status == JobStatus.JOBSTATUS_RESTARTING)
		{

      out.write("\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print("javascript:Abort(\""+js.getJobID()+"\")");
      out.write("' alt='");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"showjobstatus.Abortjob")+" "+js.getJobID());
      out.write('\'');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Abort"));
      out.write("</a>\r\n");

		}
		if (status == JobStatus.JOBSTATUS_PAUSED)
		{

      out.write("\r\n");
      out.write("\t\t\t\t\t<a href='");
      out.print("javascript:Resume(\""+js.getJobID()+"\")");
      out.write("' alt='");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"showjobstatus.Resumejob")+" "+js.getJobID());
      out.write('\'');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Resume"));
      out.write("</a>\r\n");

		}

      out.write("\r\n");
      out.write("\t\t\t\t</nobr>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"columncell\">");
      out.print("<!--jobid="+js.getJobID()+"-->");
      out.print(org.apache.manifoldcf.ui.util.Encoder.bodyEscape(js.getDescription()));
      out.write("</td><td class=\"columncell\">");
      out.print(statusName);
      out.write("</td><td class=\"columncell\">");
      out.print(startTime);
      out.write("</td><td class=\"columncell\">");
      out.print(endTime);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"columncell\">");
      out.print((js.getQueueCountExact()?"":"&gt; "));
      out.print(new Long(js.getDocumentsInQueue()).toString());
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"columncell\">");
      out.print((js.getOutstandingCountExact()?"":"&gt; "));
      out.print(new Long(js.getDocumentsOutstanding()).toString());
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"columncell\">");
      out.print((js.getProcessedCountExact()?"":"&gt; "));
      out.print(new Long(js.getDocumentsProcessed()).toString());
      out.write("</td>\r\n");
      out.write("\t\t</tr>\r\n");

	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"separator\" colspan=\"8\"><hr/></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t<tr><td class=\"message\" colspan=\"8\"><a href=\"showjobstatus.jsp\" alt=\"");
      out.print(Messages.getAttributeString(pageContext.getRequest().getLocale(),"showjobstatus.RefreshStatus"));
      out.write('"');
      out.write('>');
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.Refresh"));
      out.write("</a></td></tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");

    }
    catch (ManifoldCFException e)
    {
	out.println("Error: "+e.getMessage());

	e.printStackTrace();
    }

      out.write("\r\n");
      out.write("\t    </form>\r\n");

}
else
{

      out.write("\r\n");
      out.write("\t\t<table class=\"displaytable\">\r\n");
      out.write("\t\t\t<tr><td class=\"separator\" colspan=\"1\"><hr/></td></tr>\r\n");
      out.write("\t\t\t<tr><td class=\"message\">");
      out.print(Messages.getBodyString(pageContext.getRequest().getLocale(),"showjobstatus.PleaseTryAgainLater"));
      out.write("</td></tr>\r\n");
      out.write("\t\t</table>\r\n");

}

      out.write("\r\n");
      out.write("       </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
